language: csharp
mono: none
dotnet: 2.1.500
install:
- dotnet restore External/UnitTests/Business/
- dotnet restore External/UnitTests/MockAPI/
- dotnet restore Utils/UnitTests/
script:
- dotnet build External/UnitTests/Business/
- dotnet test External/UnitTests/Business/
- dotnet build External/UnitTests/MockAPI/
- dotnet test External/UnitTests/MockAPI/
- dotnet build Utils/UnitTests/
- dotnet test Utils/UnitTests/
